# Generated by Django 4.1.7 on 2023-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storehour',
            name='id',
        ),
        migrations.AlterField(
            model_name='storehour',
            name='store_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='storestatus',
            name='store_id',
            field=models.IntegerField(),
        ),
    ]
