# Generated by Django 4.1.7 on 2023-02-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_report', '0002_remove_storehour_id_alter_storehour_store_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=32, unique=True)),
                ('store_id', models.IntegerField()),
                ('store_timezone', models.CharField(max_length=64)),
                ('uptime_last_hour', models.DurationField()),
                ('downtime_last_hour', models.DurationField()),
                ('uptime_last_day', models.DurationField()),
                ('downtime_last_day', models.DurationField()),
                ('uptime_last_week', models.DurationField()),
                ('downtime_last_week', models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name='storehour',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storehour',
            name='store_id',
            field=models.IntegerField(),
        ),
    ]
