# Generated by Django 4.1.7 on 2023-02-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_report', '0003_storereport_storehour_id_alter_storehour_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereport',
            name='report_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='storereport',
            name='store_id',
            field=models.IntegerField(default='0'),
        ),
    ]
