# Generated by Django 4.1.7 on 2023-02-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_report', '0004_alter_storereport_report_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereport',
            name='report_id',
            field=models.CharField(max_length=100),
        ),
    ]
