# Generated by Django 4.1.7 on 2023-02-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_report', '0007_rename_timestamp_utc_storestatus_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storetimezone',
            old_name='timezone_str',
            new_name='timezonee',
        ),
    ]
